server:
  port: 8050
spring:
  application:
    # 会自动根据服务名拉取对应的dataia对应的配置文件信息
    name: com.tuling.config.nacos
  profiles:
    active: # dev
 #在配置中心通过profile进行配置，
 #只有默认的配置文件才能结合，跟服务名相同的dataid的配置文件
 #对应的dataid:${spring.application.name}
 #profile的后缀必须跟随默认配置文件的格式来
 #关于配置中心的配置才写在bootstrap中