server:
  port: 8020
#应用名称(nacos会将该名称当做服务名称)
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        namespace: public #命名空间 管理界面的服务列表
      server-addr: 192.168.1.129:8847