server:
  port: 8088
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.129:8847
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: order_route    #路由的唯一标志,路由到order
          uri: lb://order-service #需要转发到的订单 lb:使用nacos中的本地负载均衡策略 order-service 服务名
          #断言规则  用于路由规则的匹配
          predicates:
            - Path=/order/**
             #  http://localhost:8088/order-serv/order/add转发到
             #  http://localhost:8020/order-serv/order/add
            #- After=2020-12-31T23:59:59.789+08:00[Asia/Shanghai]
            #- Header=X-Request-Id,\d+  #数字正则表达式
            #- Method=GET
            #- Query=name,xx|yy  #参数中需要有xx|yy之一，否则不通过
            #- CheakAuth=nanning
          #filters:
            #- StripPrefix=1  #内置的一种过滤器，转发前去掉一层路径
            # http://localhost:8020/order/add
            #- AddRequestHeader=X-Request-color,red
            #- RedirectTo=303,https://www.baidu.com/
            #- MyRedirectToAuth=city
        #- id: store_route
      #跨域配置
#      globalcors:
#        cors-configurations:
#          '[/**]':  #允许访问的跨域资源
#            allowedOrigins:  "*" # 跨域允许的来源
#            allowedMethods:  #
#              - GET
#              - POST

#配置sentinel
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8858

